phrase:
  access_token: 4c10a6b788eb0a67889205a60201ad8df9e3939afe9161b19e44d453628a46d2
  project_id: ff36e9439ea05e3d16ccbd254125135f
  push:
    sources:
    - file: src/i18n/<locale_name>.json
      params:
        file_format: i18next
  pull:
    targets:
    - file: src/i18n/<locale_name>.json
      params:
        file_format: i18next
