#!/bin/bash
VERSION="${1:-$(npm view . version)}"
ALIAS="v${VERSION//./-}"
PROD_URL=formio-sfds.vercel.app

# make this work locally, too
if [ -f .env ]; then
  # shellcheck disable=SC1091
  source .env
fi

ROOT_URL=$(
  curl -s "https://api.vercel.com/v11/now/deployments/get?url=$PROD_URL" \
    -H "Authorization: Bearer $VERCEL_TOKEN" \
    | npx -q fx .url
)

echo "prod URL: $PROD_URL"
echo "root URL: $ROOT_URL"

if [[ "$ROOT_URL" != "" ]]; then
  ALIAS_URL="formio-sfds-${ALIAS}.vercel.app"
  echo "aliasing:"
  echo "  $ALIAS_URL → $ROOT_URL"
  npx -q vercel --scope sfds --token="$VERCEL_TOKEN" alias set "$ROOT_URL" "$ALIAS_URL"
else
  echo "no root URL found; skipping version alias"
fi
