name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  alias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: create version alias
        if: github.ref == 'refs/heads/main'
        run: |
          # pre-install CLI tools
          npm i --no-save fx vercel 

          PREFIX=formio-sfds
          PROD_URL="$PREFIX.vercel.app"
          ROOT_URL=$(
            curl -s "https://api.vercel.com/v11/now/deployments/get?url=$PROD_URL" \
              -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              | npx fx .url
          )

          echo "prod URL: $PROD_URL"
          echo "root URL: $ROOT_URL"

          if [[ "$ROOT_URL" != "" ]];
            VERSION="$(npm view . version)"
            ALIAS="v${VERSION//./-}"
            npx vercel --token="${{ secrets.VERCEL_TOKEN }}" \
              alias set "$PREFIX-$ALIAS" "$ROOT_URL"
          else
            echo "no root URL found; skipping version alias"
          fi
