name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - if: github.event_name == 'push'
        env:
          NODE_ENV: production
        run: |
          npm ci
          npm run lint
          npm run build
          npm test

      - if: github.event_name == 'push'
        uses: primer/publish@v2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - if: github.event_name == 'pull_request'
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ github.token }}
          pattern: 'dist/**/*.{css,js}'
