name: Lighthouse
on: [deployment_status]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: event debug
        run: echo '${{ toJson(github.event) }}'
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: determine branch
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          BRANCH=$(git name-rev --name-only HEAD | sed 's/~\d+$//')
          echo "BRANCH: $BRANCH"
          echo "::set-env name=BRANCH::$BRANCH"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
      - if: github.event.deployment_status.state == 'success'
        uses: treosh/lighthouse-ci-action@v3
        with:
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
          serverBaseUrl: https://lighthouse-ci-sfgov.herokuapp.com
        env:
          LHCI_GITHUB_TOKEN: ${{ github.token }}
          LHCI_COLLECT_BASE_URL: ${{ github.event.deployment_status.target_url }}
