name: Lighthouse
on: [deployment_status]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: determine branch
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          BRANCH=$(git branch --contains $GIT_REF --list --no-color | sed 's#^\* ##')
          echo "BRANCH: $BRANCH"
          echo "::set-env name=BRANCH::$BRANCH"
      - name: event debug
        run: echo '${{ toJson(github.event) }}'
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF }}
      - if: github.event.deployment_status.state == 'success'
        uses: treosh/lighthouse-ci-action@v3
        with:
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
          serverBaseUrl: https://lighthouse-ci-sfgov.herokuapp.com
        env:
          LHCI_GITHUB_TOKEN: ${{ github.token }}
          LHCI_COLLECT_BASE_URL: ${{ github.event.deployment_status.target_url }}
