name: Reports
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ github.token }}
          pattern: 'dist/**/*.{css,js}'
        env:
          NODE_ENV: production
