name: Reports
on: [pull_request]

jobs:
  build:
    if: secrets.NPM_AUTH_TOKEN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ github.token }}
          pattern: 'dist/**/*.{css,js}'
          exclude: 'dist/**/example*'
