name: Reports
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ github.token }}
          pattern: 'dist/**/*.{css,js}'
          exclude: 'dist/**/example*'
